import { defineStore } from "pinia";

export const useModelStore = defineStore("model", () => {
  const models = {
    "page.index": {
      id: 11,
      name: "首頁",
      key: "page.index",
      attribute_data: {
        carousel: {
          more: false,
          items: [
            {
              url: "https://asdasd.com",
              image: "https://picsum.photos/id/11/1000/300",
              image_m: "https://picsum.photos/id/11/200/200",
              new_page: true,
            },
            {
              url: "https://asdasd.com",
              image: "https://picsum.photos/id/12/1000/300",
              image_m: "https://picsum.photos/id/12/200/200",
              new_page: true,
            },
          ],
        },
        carousel_brand: {
          more: true,
          items: [
            {
              id: 1,
              name: "麥當勞",
              main_image: "https://picsum.photos/id/21/400/400",
              media: null,
              type: null,
              video: null,
              description: null,
              title: null,
              sub_title: null,
              sale_price: null,
              category: null,
            },
            {
              id: 2,
              name: "肯德基",
              main_image: "https://picsum.photos/id/22/400/400",
              media: null,
              type: null,
              video: null,
              description: null,
              title: null,
              sub_title: null,
              sale_price: null,
              category: null,
            },
            {
              id: 6,
              name: "test",
              main_image: "https://picsum.photos/id/23/400/400",
              media: null,
              type: null,
              video: null,
              description: null,
              title: null,
              sub_title: null,
              sale_price: null,
              category: null,
            },
            {
              id: 7,
              name: "qaaaaaa",
              main_image: "https://picsum.photos/id/24/400/400",
              media: null,
              type: null,
              video: null,
              description: null,
              title: null,
              sub_title: null,
              sale_price: null,
              category: null,
            },
          ],
        },
        carousel_product: {
          more: true,
          items: [
            {
              id: 1,
              name: "產品11",
              main_image: "https://picsum.photos/id/111/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 2,
              name: "產品22",
              main_image: "https://picsum.photos/id/112/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 3,
              name: "產品33",
              main_image: "https://picsum.photos/id/113/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 4,
              name: "產品",
              main_image: "https://picsum.photos/id/114/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 5,
              name: "產品",
              main_image: "https://picsum.photos/id/115/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
          ],
        },
      },
    },
    "page.brand_and_product": {
      id: 12,
      name: "品牌與產品",
      key: "page.brand_and_product",
      attribute_data: {
        seo: {
          url: "http://asdas.com",
          title: "test",
          keyword: ["test"],
          description: "test",
        },
        page_header: {
          data: ["product", "恭喜發財", "新年快樂"],
          name: "test",
        },
        carousel_product: {
          more: true,
          items: [
            {
              id: 1,
              name: "產品11",
              main_image: "https://picsum.photos/id/111/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 2,
              name: "產品22",
              main_image: "https://picsum.photos/id/112/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 3,
              name: "產品33",
              main_image: "https://picsum.photos/id/113/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 4,
              name: "產品",
              main_image: "https://picsum.photos/id/114/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
            {
              id: 5,
              name: "產品",
              main_image: "https://picsum.photos/id/115/300/300",
              media: null,
              type: null,
              video: null,
              description: "A",
              title: null,
              sub_title: null,
              sale_price: 9000,
              category: null,
            },
          ],
        },
      },
    },
    "page.raw_material": {
      id: 13,
      name: "原料介紹",
      key: "page.raw_material",
      attribute_data: {
        seo: {
          url: "http://youtube.com.tw",
          title: "asdada",
          keyword: ["asdsad"],
          description: "saddadada",
        },
      },
    },
    "page.news": {
      id: 14,
      name: "新訊中心",
      key: "page.news",
      attribute_data: null,
    },
    "page.information": {
      id: 15,
      name: "最新資訊",
      key: "page.information",
      attribute_data: null,
    },
    "page.media": {
      id: 16,
      name: "影音專區",
      key: "page.media",
      attribute_data: null,
    },
    "page.contact_us": {
      id: 17,
      name: "聯絡我們",
      key: "page.contact_us",
      attribute_data: null,
    },
    "page.firm": {
      id: 18,
      name: "廠商專區",
      key: "page.firm",
      attribute_data: null,
    },
    "page.about_us": {
      id: 19,
      name: "關於大樹",
      key: "page.about_us",
      attribute_data: {
        seo: {
          url: "http://localhost.kr/asdas",
          title: "111",
          keyword: ["111", "444"],
          description: "444",
        },
      },
    },
  };
  return { models };
});
